apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "twlink.fullname" . }}-frontend
  labels:
    {{- include "twlink.frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "twlink.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "twlink.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "twlink.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.frontend.livenessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.frontend.livenessProbe.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.frontend.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.frontend.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.frontend.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.frontend.readinessProbe.failureThreshold }}
            initialDelaySeconds: {{ .Values.frontend.readinessProbe.initialDelaySeconds }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
          {{- range $key, $val := .Values.frontend.env }}
            - name: {{ $key | quote }}
              value: {{ $val | quote }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
